name: Update Alerts Data

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checkout without using default GITHUB_TOKEN
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: pip install feedparser

      # Fetch alerts
      - name: Fetch Alerts
        run: python scripts/fetch_alerts.py

      # Commit changes
      - name: Commit JSON updates
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/*.json
          git commit -m "Update alerts [skip ci]" --allow-empty

      # Push changes using PAT
      - name: Push using PAT
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://$PAT_TOKEN@github.com/${{ github.repository }}.git
          git push origin HEAD:main
