name: Update Alerts Data

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install feedparser
      - name: Fetch Alerts
        run: python scripts/fetch_alerts.py
      - name: Validate JSON
        run: |
          python - <<'PY'
          import json, glob, sys
          for f in glob.glob("data/*.json"):
              try:
                  json.load(open(f))
              except Exception as e:
                  print(f"Invalid JSON {f}: {e}")
                  sys.exit(1)
          PY
      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/*.json
          git commit -m "Update alerts [skip ci]" --allow-empty
          git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} HEAD:main
